config/routes.rb
Text2speech::Application.routes.draw do
  get "/", :to => "text_to_speech#index", :as => :root
  post "/", :to => "text_to_speech#create", :as => false

  get "languages/", :to => "languages#index", :as => :languages

  get "languages/new", :to => "languages#new", :as => :new_language
  post "languages/new", :to => "languages#create", :as => false

  get "languages/delete/:id", :to => "languages#delete", :as => :delete_language 
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :name, :value

  validates_presence_of :name, :value
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/language_controller.rb
class LanguageController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def new
    @language = Language.new
  end

  def create
    @language = Language.new(params[:language])

    if @language.save
      flash.now[:notice] = t("flash.languages.create.notice")
      redirect_to languages_path
    else
      flash.now[:error] = t("flash.languages.create.error")
    end
  end

  def delete
    @language = Language.find(params[:id])
    @language.destroy

    flash[:info] = t("flash.languages.delete")
    redirect_to languages_path
  end

  def index
    @languages = Language.all
  end
end

app/controllers/text_to_speech_controller.rb
class TextToSpeechController < ApplicationController
  def index
    @languages = Language.all
    @languages.sort! { |a, b| a.name.downcase <=> b.name.downcase }
  end

  def create
    translator = BingTranslator.new('jemaf', 'RYpFKXu5O/Q5/mAZ/KAfbx+LdUSWNorD6hjPEduzkVg=')
    text = params[:translation_text]
    lang = params[:languages]

    if text.present?
      file_name = "audio/" + Time.now.to_i.to_s + ".mp3"
      audio = translator.speak "#{text}", :language => "#{lang}", 
            :format => 'audio/mp3', :options => 'MaxQuality'
      open(file_name, 'wb') { |f| f.write audio }
      send_file file_name
    else
      flash[:error] = t("flash.tts.no_message")
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/languages/index.html.erb
<h1><%= t("languages.index.title") %></h1>

<p><%= t("languages.index.description") %></p>

<% if flash[:info] %>
<div class="alert alert-info">
  <%= flash[:info] %>
</div>
<% end %>

<div class="row-fluid">
  <div class="span4"><h4><%= t("activerecord.attributes.language.name") %><h4></div>
  <div class="span4"><h4><%= t("activerecord.attributes.language.value") %><h4></div>
</div>

<% @languages.each do |language| %>
<div class="row-fluid">
  <div class="span4"><%= language.name %></div>
  <div class="span4"><%= language.value%></div>
  <div class="span1">
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    delete_language_path(language),
    :method => :delete,
    :class => 'btn btn-mini btn-danger' %>
  </div>
</div>
<% end %>
<%= link_to t("languages.index.new_language"), new_language_path %>

app/views/languages/new.html.erb
<h1><%= t("languages.new.title") %></h1>

<p><%= t("languages.new.description") %></p>

   <% if flash[:notice] %>
    <div class="alert alert-success">
      <p><%= flash[:notice] %></p>
    </div>
    <% end %>
    <% if flash[:error] %>
    <div class="alert alert-error">
      <% if @language.errors.any? %>
      <ul>
        <% @language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
    </div>
    <% end %>

<%= simple_form_for @language, :url => new_language_path do |f| %>
  <%= f.input :name %>
  <%= f.input :value %>
  <%= f.submit%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Text2speech</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="span9"><%= yield %></div>
<div class="span3">
<p>
<h3><%=t("application.about.howitworks.title")%></h3>

<p> <%=t("application.about.howitworks.text")%> </p>

<ol>
  <li><%=t("application.about.howitworks.step1")%></li>
  <li><%=t("application.about.howitworks.step2")%></li>
  <li><%=t("application.about.howitworks.step3")%></li>
  <li><%=t("application.about.howitworks.step4")%></li>
</ol>
</div>

</body>
</html>

app/views/text_to_speech/index.html.erb
<h1><%= t("tts.index.title") %></h1>


  <% if flash[:notice] %>
    <div class="alert alert-success">
      <p><%= flash[:notice] %></p>
    </div>
    <% end %>
    <% if flash[:error] %>
    <div class="alert alert-error">
      <%= flash[:error] %>
    </div>
  <% end %>

<form method="post">
  <p><%= t("tts.index.text.name") %></p>
  <p>
    <textarea name="translation_text" class="input-xxlarge" rows="20"></textarea>
  </p>
   <p><%= t("tts.index.languages.name") %></p>

   <p>
    <select name="languages">
      <% if !@languages.blank? %>
        <% for language in @languages %>
          <option value="<%= language.value %>"><%= language.name %></option>
        <% end %>
      <% end %>
    </select>
   </p>

  <p>
    <input class="btn btn-large btn-primary" type="submit" value="Submit"></submit>
  </p>
</form>